// <auto-generated />
using App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Migrations
{
    [DbContext(typeof(BlogginContext))]
    partial class BlogginContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("App.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Url");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            Url = "http://model-seeding.com"
                        });
                });

            modelBuilder.Entity("App.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlogId");

                    b.Property<string>("Content");

                    b.Property<string>("Popularity");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            BlogId = 1,
                            Content = "First post test",
                            Title = "First post"
                        },
                        new
                        {
                            PostId = 2,
                            BlogId = 1,
                            Content = "Second post content",
                            Title = "Second post"
                        });
                });

            modelBuilder.Entity("App.Post", b =>
                {
                    b.HasOne("App.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("App.Name", "AuthorName", b1 =>
                        {
                            b1.Property<int>("PostId");

                            b1.Property<string>("First");

                            b1.Property<string>("Last");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.HasOne("App.Post")
                                .WithOne("AuthorName")
                                .HasForeignKey("App.Name", "PostId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.HasData(
                                new
                                {
                                    PostId = 1,
                                    First = "Carlos",
                                    Last = "Carlin"
                                },
                                new
                                {
                                    PostId = 2,
                                    First = "Funny",
                                    Last = "Furniture"
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
